# Generated by Django 2.1.7 on 2019-03-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbAdmin',
            fields=[
                ('admin_id', models.IntegerField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=50)),
                ('admin_password', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tb_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbBookinfo',
            fields=[
                ('bookid', models.IntegerField(db_column='BookID', primary_key=True, serialize=False)),
                ('bookname', models.CharField(db_column='BookName', max_length=50)),
                ('bookintroduce', models.TextField(db_column='BookIntroduce')),
                ('author', models.CharField(db_column='Author', max_length=50)),
                ('company', models.CharField(db_column='Company', max_length=50)),
                ('bookurl', models.CharField(db_column='BookUrl', max_length=200)),
                ('marketprice', models.FloatField(db_column='MarketPrice')),
                ('hotprice', models.FloatField(db_column='HotPrice')),
                ('isrefinment', models.BooleanField(db_column='Isrefinment')),
                ('ishot', models.BooleanField(db_column='IsHot')),
                ('isdiscount', models.BooleanField(db_column='IsDiscount')),
                ('loaddate', models.DateTimeField(db_column='LoadDate')),
            ],
            options={
                'db_table': 'tb_BookInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbClass',
            fields=[
                ('classid', models.IntegerField(db_column='ClassID', primary_key=True, serialize=False)),
                ('classname', models.CharField(db_column='ClassName', max_length=50)),
                ('categoryurl', models.CharField(db_column='CategoryUrl', max_length=50)),
            ],
            options={
                'db_table': 'tb_Class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbDetail',
            fields=[
                ('detailid', models.IntegerField(db_column='DetailID', primary_key=True, serialize=False)),
                ('num', models.IntegerField(db_column='Num')),
                ('totalprice', models.FloatField(db_column='TotalPrice')),
                ('remark', models.CharField(db_column='Remark', max_length=200)),
            ],
            options={
                'db_table': 'tb_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageid', models.IntegerField(db_column='ImageID')),
                ('imagename', models.CharField(db_column='ImageName', max_length=50)),
                ('imageurl', models.CharField(db_column='ImageUrl', max_length=200)),
            ],
            options={
                'db_table': 'tb_image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbMember',
            fields=[
                ('memberid', models.IntegerField(db_column='MemberID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='UserName', max_length=50)),
                ('password', models.CharField(db_column='Password', max_length=50)),
                ('realname', models.CharField(db_column='RealName', max_length=50)),
                ('sex', models.BooleanField(blank=True, db_column='Sex', null=True)),
                ('phonecode', models.CharField(blank=True, db_column='Phonecode', max_length=20, null=True)),
                ('email', models.CharField(db_column='Email', max_length=50)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=200, null=True)),
                ('postcode', models.CharField(db_column='PostCode', max_length=10)),
                ('loaddate', models.DateTimeField(blank=True, db_column='LoadDate', null=True)),
            ],
            options={
                'db_table': 'tb_Member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbOrderinfo',
            fields=[
                ('orderid', models.IntegerField(db_column='OrderID', primary_key=True, serialize=False)),
                ('orderdate', models.DateTimeField(db_column='OrderDate')),
                ('booksfee', models.FloatField(db_column='BooksFee')),
                ('shipfee', models.FloatField(db_column='ShipFee')),
                ('totalprice', models.FloatField(db_column='TotalPrice')),
                ('shiptype', models.CharField(db_column='ShipType', max_length=50)),
                ('receivername', models.CharField(db_column='ReceiverName', max_length=50)),
                ('receiverphone', models.CharField(db_column='ReceiverPhone', max_length=20)),
                ('receiveraddress', models.CharField(db_column='ReceiverAddress', max_length=200)),
                ('receiveremail', models.CharField(db_column='ReceiverEmail', max_length=50)),
                ('isconfirm', models.BooleanField(db_column='IsConfirm')),
                ('issend', models.BooleanField(db_column='IsSend')),
                ('isend', models.BooleanField(db_column='IsEnd')),
                ('adminid', models.BooleanField(blank=True, db_column='AdminID', null=True)),
                ('confirmtime', models.DateTimeField(blank=True, db_column='ConfirmTime', null=True)),
                ('receiverpostcode', models.CharField(db_column='ReceiverPostCode', max_length=10)),
            ],
            options={
                'db_table': 'tb_OrderInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('picture', models.FileField(upload_to='./upload/')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
